# Example sites to look at:
# 1. https://github.com/jekyll/jekyll/blob/master/docs/ - this folder contains all of the actual
#    Jekyll website files for this website here: https://jekyllrb.com/.
# 2. https://github.com/jekyll/minima
# 3. https://jamstackthemes.dev/theme/devlopr/ - very nice-looking, with a really cool auto-typing
#    text string at the top, and a nice light/dark mode button too.
#   1. GitHub: https://github.com/sujaykundu777/devlopr-jekyll
#   2. Live demo: https://devlopr.netlify.app/
# 4. https://jekyllcodex.org/
#   1. GitHub: https://github.com/jhvanderschee/jekyllcodex
# 5. Example containing "categories" too:
#   1. See PlanetJekyll plugins repo:
#      https://github.com/planetjekyll/awesome-jekyll-plugins#tags--taggings-categories--categorizations
#   2. Another example by CodinFox:
#     1. https://codinfox.github.io/dev/2015/03/06/use-tags-and-categories-in-your-jekyll-based-github-pages/
#     2. live demo of Categories: http://codinfox.github.io/blog/categories/
#     3. live demo of Tags: http://codinfox.github.io/blog/tags/

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# title: GabrielStaples.com
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# GS: see: https://github.com/jekyll/minima/blob/38a84a949f9753c4542e25f422935f59b4913053/_includes/social.html
# - commented out so I can use the "minima.social_links" ones below for the latest jekyll/minima
#   remote_theme (ie: latest master branch on GitHub) instead!
# twitter_username: jekyllrb--fff
# github_username:  jekyll

# Build settings
# theme: minima # GS: commented out so I can use the one below
# GS; see: https://github.blog/2017-11-29-use-any-theme-with-github-pages/
#          https://github.com/jekyll/minima
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  # GS-added:
  # See: https://jekyllrb.com/docs/step-by-step/10-deployment/
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# ---------------- GS Additions: -----------------------

# Use Github-Flavored-Markdown (GFM); see:
# https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll
markdown: GFM

# Note: supports Linux globbing
exclude:
  - /GitHub Pages Help, Tips & Tricks/*
  - /Jekyll Help, Tips & Tricks/*
  - /*/readme.md
  - /*/README.md
  - /README.md
  - /Welcome_to_GitHub_Pages.md
  - /*/Welcome_to_GitHub_Pages.md
  - /disabled/*
  - /*/disabled/*


title: GabrielStaples.com Home
author:
  name: Gabriel Staples
  # email: your-email@domain.com
# description: > # this means to ignore newlines until "show_excerpts:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Gabriel Staples, covering anything from software development, C, C++, Python,
  electronics and electrical engineering, radio control aircraft, aeronautical engineering,
  basic life skills or life hacks, or even views on life, personal opinions, and political and
  religious discussions, beliefs, and points of view.

show_excerpts: false # set to true to show excerpts (1st paragraph of each post) as a preview
    # on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # GS: see also https://github.com/jekyll/minima/blob/master/_config.yml
  social_links:
    twitter: eRCaGuy
    github:  ElectricRCAircraftGuy
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: ercaguy
    linkedin: gabriel-staples
    # pinterest: jekyll
    youtube: ElectricRCAircraftGuy
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: ElectricRCAircraftGuy
      # instance: gitlab.com/ElectricRCAircraftGuy
    # - username: jekyll2
    #   instance: example.com

  # GS: see: https://github.com/jekyll/minima#skins
  skin: classic
  # skin: dark
  # skin: solarized
  # skin: solarized-dark

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md



