# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
remote_theme             : "mmistakes/minimal-mistakes@4.20.2"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "GabrielStaples.com home"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
# name                     : "Your Name"
name                     : "Gabriel Staples"
# description              : "An amazing website."
# GS note: you can use YAML anchors and aliases to use this variable again later for the `bio`
# field! See:
# https://talk.jekyllrb.com/t/is-it-possible-to-assign-one-variable-in-config-yml-to-another/5175/2
description: &description_ >- # this means to ignore newlines until the next item in the list
  My personal website, covering anything from software development, C, C++, Python,
  electronics and electrical engineering, radio control aircraft, aeronautical engineering,
  basic life skills or life hacks, or even views on life, personal opinions, and political and
  religious discussions, beliefs, and points of view.
# url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
url                      : "https://gabrielstaples.com"
baseurl                  : # the subpath of your site, e.g. "/blog"
# repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
repository               : "ElectricRCAircraftGuy/ElectricRCAircraftGuy.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : true # true, false (default)
# GS: default for this theme is 200 wpm, but a quick Google search shows that is typical for NON-technical writing, so
# let's make it 100 wpm for my site!
words_per_minute         : 100
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
# GS: https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-author
author:
  # name             : "Your Name"
  name             : "Gabriel Staples"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  # bio              : "I am an **amazing** person."
  # bio              : "{{ site.description }}" # GS: doesn't work :( Use YAML anchors and aliases
                                                # instead!
  bio              : *description_
  # location         : "Somewhere"
  location         : "San Francisco"
  email            :
  links:
    - label: "Email"
      icon:  "fas fa-fw fa-envelope-square"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon:  "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon:  "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon:  "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon:  "fab fa-fw fa-github"
      # url: "https://github.com/"
    - label: "Instagram"
      icon:  "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"
    ###########
    # GS added:
    ###########
    - label: "www.ElectricRCAircraftGuy.com"
      icon:  "fas fa-fw fa-link"
      url:   "https://ElectricRCAircraftGuy.com"
    - label: "GitHub"
      icon:  "fab fa-fw fa-github"
      url:   "https://github.com/ElectricRCAircraftGuy"
    - label: "LinkedIn"
      icon:  "fab fa-linkedin"
      url:   "https://www.linkedin.com/in/gabriel-staples/"
    - label: "YouTube"
      icon:  "fab fa-youtube"
      url:   "https://www.youtube.com/ElectricRCAircraftGuy"
    - label: "Instagram"
      icon:  "fab fa-fw fa-instagram"
      url:   "https://www.instagram.com/ercaguy/"
    - label: "Twitter"
      icon:  "fab fa-fw fa-twitter-square"
      url:   &twitter_url "https://twitter.com/eRCaGuy"


# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:
    ###########
    # GS added (EXACTLY COPIED FROM ABOVE!)
    ###########
    - label: "www.ElectricRCAircraftGuy.com"
      icon:  "fas fa-fw fa-link"
      url:   "https://ElectricRCAircraftGuy.com"
    - label: "GitHub"
      icon:  "fab fa-fw fa-github"
      url:   "https://github.com/ElectricRCAircraftGuy"
    - label: "LinkedIn"
      icon:  "fab fa-linkedin"
      url:   "https://www.linkedin.com/in/gabriel-staples/"
    - label: "YouTube"
      icon:  "fab fa-youtube"
      url:   "https://www.youtube.com/ElectricRCAircraftGuy"
    - label: "Instagram"
      icon:  "fab fa-fw fa-instagram"
      url:   "https://www.instagram.com/ercaguy/"
    - label: "Twitter"
      icon:  "fab fa-fw fa-twitter-square"
      url:   &twitter_url "https://twitter.com/eRCaGuy"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
  # Added by GS:
  - /0--Old/*
  - /GitHub Pages Help, Tips & Tricks/*
  - /Jekyll Help, Tips & Tricks/*
  - /*/readme.md
  - /*/README.md
  - /README.md
  - /Welcome_to_GitHub_Pages.md
  - /*/Welcome_to_GitHub_Pages.md
  - /disabled/*
  - /*/disabled/*
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
# GS: use Github Flavored Markdown instead! Among other things, kramdown won't automatically turn a
# regular, pasted link into a clickable link, but GFM will! HOWEVER, kramdown DOES produce
# tables of contents with `toc: true`, but GFM will NOT! :(
# - Solution: just look for a Sublime Text plugin instead? This has the advantage of working on my
# regular GitHub readmes too, and NOT just on my GitHub pages site! See what you can find!
# UPDATE: see my answer here!:
# https://stackoverflow.com/questions/11948245/markdown-to-create-pages-and-table-of-contents/64656967#64656967
# markdown: GFM
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # 10 # amount of posts to show; GS (on home page) default: 5
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# GS: list of GitHub Pages whitelisted plugins: https://pages.github.com/versions/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  # Added by GS:
  - jekyll-seo-tag

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  # Added by GS:
  - jekyll-seo-tag


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      # GS show date: https://mmistakes.github.io/minimal-mistakes/docs/configuration/#post-dates
      show_date: true
